name: Makefile CI

on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build release
        run: |
          make
          tar -cJf reforward-tcp.tar.xz release/reforward-tcp
          tar -cJf reforward-lite-tcp.tar.xz release/reforward-lite-tcp
          tar -cJf reforward-udp.tar.xz release/reforward-udp
          tar -cJf readme.tar.xz release/readme
          mkdir dist
          mv *.tar.xz dist
      - name: Upload release 
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: ./dist
      - name: Release and upload assets
        uses: softprops/action-gh-release@v0.1.6
        with:
          name: ${{ env.RELEASE_NAME }}
          tag_name: ${{ env.TAG_NAME }}
          draft: false
          prerelease: false
          files: |
            ./dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.ITHUB_TOKEN }}
