name: Makefile CI

on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build release
        run: |
          make
          xz -9 ./release/reforward-tcp
          xz -9 ./release/reforward-lite-tcp
          xz -9 ./release/reforward-udp
          xz -9 ./release/readme
      - name: Upload release 
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: ./release
      - name: Release and upload assets
        uses: softprops/action-gh-release@v0.1.6
        with:
          name: ${{ env.RELEASE_NAME }}
          tag_name: ${{ env.TAG_NAME }}
          draft: false
          prerelease: false
          files: |
            ./release/*
        env:
          GITHUB_TOKEN: ${{ secrets.ITHUB_TOKEN }}
